# Where CIS-CAT will live on target systems
cis_cat_install_dir: /opt/cis-cat
cis_cat_report_dir: /var/tmp/cis-cat-reports

# CIS profile
cis_cat_profile: "Level 1 - Server"

# Linux benchmark (Ubuntu 22.04)
cis_cat_linux_benchmark: CIS_Ubuntu_Linux_22.04_LTS_Benchmark_v1.0.0-xccdf.xml

# Windows benchmark (Server 2022)
cis_cat_windows_benchmark: CIS_Microsoft_Windows_Server_2022_Benchmark_v1.0.0-xccdf.xml

# Location of CIS-CAT binaries inside Semaphore container
cis_cat_src_dir: /cis-cat/Assessor
