- name: Provision VMs on Proxmox
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../inventories/vms.yml

  tasks:
    - name: Create all defined VMs
      include_role:
        name: proxmox_create_vm
      loop: "{{ vms }}"
      loop_control:
        loop_var: vm

    - name: Write runtime inventory file
      copy:
        dest: ../inventories/runtime.yml
        content: "{{ runtime_inventory | to_nice_yaml }}"

